### ISSUE TITLE
some questions 

### ISSUE THREAD

**Issue by zc994646659** [Cloudiiink/pyw90#9]
Dear Sir

I hope this email finds you well. I am writing to seek guidance regarding the determination of an appropriate fitting window for my analysis.

After carefully studying the relevant materials, I am still uncertain about how to determine the fitting window. Specifically, I have encountered difficulties in understanding how to generate a suggested interval for fitting.

Allow me to provide some context. Currently, I am working with a set of 32 Wannier functions, and I would like to fit a band within an energy range of 2eV above and below the Fermi level. However, I am unsure about the steps involved in generating a suitable interval for fitting.

Could you please provide me with some advice or guidance on how to proceed in determining the suggested window?

Thank you very much for your attention and support. I look forward to your response.

Sincerely,
zhouchao

**Comment by Cloudiiink** [comment]
It seems like you may have questions about how to use `Wannier90` instead of `pyw90`. To gain a better understanding of the initial projection and energy window (`pyw90` aims to analyze and test input parameters easily.), I suggest running the `Wannier90` Tutorial examples (https://wannier.org/support/) and example of GaAs in `pyw90` before you run your project. 

The review article by Marzari et al. (2012) on maximally localized Wannier functions (MLWF) also provides a comprehensive overview of the theory and applications of MLWF. Hope this helps!

> Marzari, N., Mostofi, A.A., Yates, J.R., Souza, I., Vanderbilt, D., 2012. Reviews of Modern Physics 84, 1419–1475.

**Comment by Cloudiiink** [comment]
Upon private consultation, it was determined that the current version of `pyw90` doesn't support spinful system.
Here is a typical error output using command `pyw90 eig suggest -e 5 15` to generate a possible energy window:

```
Traceback (most recent call last):
  File "/public/home/baokuo28/magus/bin/pyw90", line 8, in <module>
    sys.exit(main_cli())
  File "/public/home/baokuo28/magus/lib/python3.9/site-packages/pyw90/pyw90_cli.py", line 352, in main_cli
    args.func(args)
  File "/public/home/baokuo28/magus/lib/python3.9/site-packages/pyw90/pyw90_cli.py", line 273, in eig
    w90 = W90(eig=args.eig,
  File "/public/home/baokuo28/magus/lib/python3.9/site-packages/pyw90/lib/w90.py", line 58, in __init__
    self.read_eigenval()
  File "/public/home/baokuo28/magus/lib/python3.9/site-packages/pyw90/lib/w90.py", line 86, in read_eigenval
    dump = np.array(
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (603,) + inhomogeneous part.
```

This problem comes from the new columns introduced in `EIGENVAL` file for spinful system. Here is a typical `EIGENVAL` for spinful system:

```
   12   12    1    2
  0.9361768E+01  0.5188856E-09  0.5064479E-09  0.4274967E-09  0.1000000E-15
  1.000000000000000E-004
  CAR 
 unknown system                          
    116   1200    120
 
  0.0000000E+00  0.0000000E+00  0.0000000E+00  0.8333333E-03
    1      -40.483756    -40.483756   1.000000   1.000000
    2      -40.480183    -40.480183   1.000000   1.000000
    3      -40.437503    -40.437503   1.000000   1.000000
    4      -40.426142    -40.426142   1.000000   1.000000
    5      -40.347259    -40.347259   1.000000   1.000000
...
```

But for non-spinful system, e.g. GaAs in tests folder, the data in `EIGENVAL` file looks like:
```
    2    2    1    1
  0.2376593E+02  0.4065993E-09  0.4065993E-09  0.4065993E-09  0.5000000E-15
  1.000000000000000E-004
  CAR 
 GaAs                                    
     18    120     16
 
  0.0000000E+00  0.0000000E+00  0.0000000E+00  0.2962963E-03
    1      -11.255844   1.000000
    2      -11.255843   1.000000
...
```

**Comment by Lijiuyin** [comment]
Dear sir
Sorry to bother, I read the above problem discussion and I have similar doubts, I found that the calculated EIGENVAL file with SOC is consistent with the non-spinful system, we know that with the SOC system, the number of energy bands should be doubled. For example, without SOC in wannier90, I need 78 bands. But with SOC, I need 156（value of num_wann ） bands, but I am running 'pyw90 pre dos --path . -e -4.85 20 --extra' command gives the following:
Dis frozen window table
The table is sorted according to the percentage of pdos/tdos.
If you want to see `dis_win_min(max)` suggestion, please use `pyw90 eig suggest` menu.
     dis_froz_min  dis_froz_max   N       pdos       tdos   percent
14       2.738141      9.432657  78  78.269155  94.001511  0.832637
12       2.536791      8.672642  78  75.261777  91.590000  0.821725
15       2.754595      9.642980  78  75.859495  92.353371  0.821405
24       3.434191     10.819870  78  61.310056  74.819549  0.819439
13       2.678902      8.778362  78  71.441945  87.184462  0.819434...
The above parameter N only shows 78, I think it should affect the accuracy of the energy window here, I hope to get your guidance.
Thank you very much for your attention and support. I look forward to your response.

Sincerely,
JiuYin Li
